version: '3.9'

services:
  imlclax_app:
    user: "root"  #Assim o Django roda como root e sempre terá permissão para escrever.
    container_name: imlclax_app
    build:
      context: .
    ports:
      - "8989:8989"
    volumes:
      - ./iMlclaX_App:/iMlclaX_App
      - ./data/web/media:/data/web/media/
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - imlclax_psql

  imlclax_psql:
    container_name: imlclax_psql
    image: postgres:16-alpine
    restart: always
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./dotenv_files/.env
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: imlclax_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: imlclax@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin-imlclax
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "15050:80"   # ✅ porta externa ajustada
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
      - ./pgadmin_servers.json:/pgadmin4/servers.json
    depends_on:
      - imlclax_psql
